### ISSUE TITLE
GitHub Actions & npm install error 

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/Gatsby#1]
# GitHub Actions & npm install error 

```code
npm ERR! this command with --force, or --legacy-peer-deps
```

https://github.com/xgqfrms/Gatsby-Tutorials-All-In-One/runs/7604782756?check_suite_focus=true

![image](https://user-images.githubusercontent.com/7291672/182204412-ce7469ab-b3e5-4bb6-8a92-ac878f675ffe.png)

**Comment by xgqfrms** [comment]
```yml
      - name: Install ESLint
        run: |
          npm install eslint@8.10.0 --force
          npm install @microsoft/eslint-formatter-sarif@2.1.7 --force
```

https://github.com/xgqfrms/Gatsby-Tutorials-All-In-One/blob/master/.github/workflows/eslint.yml
